version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config/
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped

  mqtt-exporter:
    image: fhemberger/mqtt_exporter
    volumes:
      - ./mqtt-exporter/config.yaml:/usr/src/app/conf
    ports:
      - "9344:9344"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/config.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - "80:3000"
    restart: unless-stopped

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./home-assistant/config:/config
      - /home/pi/.ssh/id_rsa_homeassistant:/config/id_rsa_homeassistant
    ports:
      - "8123:8123"
    restart: unless-stopped
